<?php
define('HTML_WIDTH','750');
define('LEFT_NAVIGATION_WIDTH','20%');
define('HEADING_FONT_FACE','Verdana, Arial, Helvetica');
define('HEADING_FONT_SIZE','2');
define('HEADING_FONT_COLOR','#FFFFFF');
define('TEXT_FONT_FACE','Arial');
define('TEXT_FONT_SIZE','2');
define('TEXT_FONT_COLOR','#336699');
define('REQUIRED_TEXT_FONT_FACE','MS Sans Serif');
define('REQUIRED_TEXT_FONT_SIZE','2');
define('REQUIRED_TEXT_FONT_COLOR','#FF9224');
define('ERROR_TEXT_FONT_FACE','arial');
define('ERROR_TEXT_FONT_SIZE','2');
define('ERROR_TEXT_FONT_COLOR','#FF0000');
define('DISPLAY_TEXT_FONT_FACE','MS Sans Serif');
define('DISPLAY_TEXT_FONT_SIZE','1');
define('DISPLAY_TEXT_FONT_COLOR','#000000');
define('DISPLAY_LINE_BGCOLOR_FIRST','#FFF5E6');
define('DISPLAY_LINE_BGCOLOR_SECOND','#FFFFFF');
define('REQUIRED_STAR','<font color="red"><b>*</b></font>');
define('NEXT_FONT_FACE','Verdana, Arial');
define('NEXT_FONT_SIZE','2');
define('NEXT_FONT_COLOR','#000000');
define('TABLE_BGCOLOR','#FFFFFF');
define('TABLE_EMPLOYER','#0099FF');
define('LEFT_NAV_BG_COLOR','#FFFFFF');
define('LIST_BORDER_COLOR','#BBBBBB');
define('LIST_HEADER_COLOR','#FFFFCC');
define('TABLE_HEADING_BGCOLOR','#0099FF');
?>